### ISSUE TITLE
pypi package (0.5) will not install

### ISSUE THREAD

**Issue by Beirdo** [tedder/requests-aws4auth#1]
The tarball is missing HISTORY.rst, so the package install fails.

**Comment by sam-washington** [comment]
Thanks for the report, what install system are you using?

**Comment by sam-washington** [comment]
OK, reproduced with pip install --no-binary :all:

Will get a fixed version up tomorrow

**Comment by sam-washington** [comment]
Uploaded version 0.6 to PyPi which fixes this issue.

**Comment by Beirdo** [comment]
Thank you.  I'll try it tomorrow.

On September 8, 2015, at 13:32, Sam Washington notifications@github.com wrote:

Uploaded version 0.6 to PyPi which fixes this issue.
