### ISSUE TITLE
use role credentials?

### ISSUE THREAD

**Issue by patrickpierson** [tedder/requests-aws4auth#14]
is there a way to use a role credential with requests-aws4auth?

instead of the following:

```
awsauth = AWS4Auth(args.awsaccesskey, args.awssecretkey, args.awsregion, 'es')
```

would there be a way to not send credentials into AWS4Auth or allow it to pick up instance metadata or (in my case specifically) AWS Lambda's role key info?

**Comment by koiker** [comment]
Not only role but in the same way of boto3 get the credentials from ENV variables or /.aws/config files
In this way you can run the import without need to include static ACCESS_KEY/SECRET_KEY.

**Comment by sam-washington** [comment]
@patrickpierson Would you be able to give an example? Do you mean be able to pass it a single object with credentials?

**Comment by sam-washington** [comment]
@patrickpierson @koiker Something like described here? https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs

**Comment by koiker** [comment]
Working example:

```
import boto3
from requests_aws4auth import AWS4Auth

session = boto3.Session()
credentials = session.get_credentials()
region = os.environ['AWS_REGION']

awsauth = AWS4Auth(credentials.access_key, credentials.secret_key, region, 'es', session_token=credentials.token)
```

You don't need to hardcode your credentials in your code.

**Comment by koiker** [comment]
You can close the ticket.

**Comment by andrew-kurin** [comment]
If the boto3 session getting credentials from a role, the example would only work until credentials expire, which is one hour. For long running processes it means that they can't just keep awsauth object cached and would need to create it on each request

**Comment by koiker** [comment]
Based on documentation the boto3:
http://boto3.readthedocs.io/en/latest/guide/configuration.html

## Assume Role Provider

> Note
> This is a different set of credentials configuration than using IAM roles for EC2 instances, which is discussed in a section below.

Within the `~/.aws/config` file, you can also configure a profile to indicate that boto3 should assume a role. When you do this, boto3 will automatically make the corresponding `AssumeRole` calls to AWS STS on your behalf. It will handle in memory caching as well as refreshing credentials as needed.

And as documented in the AWS4Auth `aws4auth.py`

> This example shows how to construct an AWS4Auth object for use with STS
>     temporary credentials. The `x-amz-security-token` header is added with
>     the session token. Temporary credential timeouts are not managed -- in
>     case the temporary credentials expire, they need to be re-generated and
>     the AWS4Auth object re-constructed with the new credentials

So, even if you use STS generated credentials you need to renew before timeout.

**Comment by andrew-kurin** [comment]
Exactly. But in the case of IAM roles, when you use the example above, boto3 returns a `botocore.credentials.RefreshableCredentials` object from the `get_credentials()` call.
This object actually manages the timeouts on temporary credentials, and would return you a fresh set of credentials before the current credentials expire.
So it would be nice if AWS4Auth could accept this object as a parameter, and use it to get access_key, secret_key, session_token.

**Comment by andrew-kurin** [comment]
@koiker something along the lines https://gist.github.com/zen4ever/5103a4091de28f2f53be2ab8de2ae905
I figured out that you can actually subclass the AWS4Auth and add this capability to work with self-refreshing botocore credentials

**Comment by landonsilla** [comment]
Is this still a problem? I ran into this exact same problem, and applied @zen4ever 's solution.  It would be great if this fix were applied to the repo directly such that no explicit refreshing was necessary.

**Comment by teemuy** [comment]
My PR https://github.com/tedder/requests-aws4auth/pull/37 would fix this too, as noted by rxvt.

**Comment by tedder** [comment]
#37 merged.
