### ISSUE TITLE
FYI: works with Tornado's HTTPRequest objects

### ISSUE THREAD

**Issue by jvhellemond** [tedder/requests-aws4auth#15]
**Not an issue, just an FYI**
requests-aws4auth seems to work fine with [Tornado's](https://github.com/tornadoweb/tornado) [`HTTPRequest` objects](https://github.com/tornadoweb/tornado/blob/master/tornado/httpclient.py#L289). I use it for lightweight AWS requests, like uploading files to S3. This saves a lot of `boto3` or `botocore` dependencies and code and I can use the asynchronous [`AsyncHttpClient`](https://github.com/tornadoweb/tornado/blob/master/tornado/httpclient.py#L106), leveraging Tornado's async/non-blocking/ioloop features.

The `HTTPRequest` object exposes a `headers` dict and a `body` property, which seems to be all `AWS4Auth` needs.

For example:

``` python
auth = requests_aws4auth.AWS4Auth(<key>, <secret>, "eu-west-1", "s3")
req = tornado.httpclient.HTTPRequest(<endpoint>, method="PUT", body=<body>)
signed_req = auth(req)

tornado.httpclient.AsyncHTTPClient().fetch(signed_req)
```

That is all, thanks ;)

**Comment by sam-washington** [comment]
Well, `AWS4Auth` actually makes a reference to `req.method` too, but if it's working, great! Thanks for letting us know :)
