### ISSUE TITLE
You can add IVONA to 'Supported Services'

### ISSUE THREAD

**Issue by pawelad** [tedder/requests-aws4auth#16]
Hi,

Awesome project, thanks a bunch - you saved me a lot of hassle : )
I just wanted to let you know that you can add [IVONA Speech Cloud API](https://www.ivona.com/us/for-business/speech-cloud/) to list of supported services in README - I use it [here](https://github.com/Pythonity/python-ivona-api) and it works like a charm.

**Comment by sam-washington** [comment]
Thanks @pawelad, I'll include it in the next release
