### ISSUE TITLE
Update project to BETA or PRODUCTION/STABLE

### ISSUE THREAD

**Issue by koiker** [tedder/requests-aws4auth#33]
Acording to List classifiers of PyPi I believe that we can move this project from ALPHA to BETA  safely and plan to put the version to PROD if all the tests/validations are satisfied
https://pypi.python.org/pypi?%3Aaction=list_classifiers
Development Status :: 4 - Beta
Development Status :: 5 - Production/Stable

**Comment by tedder** [comment]
done in v1.0.1.
