### ISSUE TITLE
Version bump to 0.7?

### ISSUE THREAD

**Issue by mathom** [tedder/requests-aws4auth#5]
To install off pypi I think we need a version bump or update for 0.6 to get https://github.com/sam-washington/requests-aws4auth/pull/2 out in the wild. How do you prefer to do that?

**Comment by einvalentin** [comment]
yeah! that would be great :+1:

**Comment by sam-washington** [comment]
Yep, on it guys, will have 0.7 up this week. Sorry for the wait!

**Comment by mathom** [comment]
No problem, thanks for the help!

**Comment by sam-washington** [comment]
0.7 is up on pypi.
