### ISSUE TITLE
Incorrect signature when send request with spaces in query parameters

### ISSUE THREAD

**Issue by bnorris823** [tedder/requests-aws4auth#54]
I am trying to and a request to the api gateway with query string parameters that have a value that includes spaces. However, I keep getting a 403 explaining that I have a signature that does not match. When I replace the spaces with '+' the  request works fine. How do I get it to work with the spaces?
```
def get_auth():
    # uses aws creds from env to get auth header for requests to api gateway endpoints

    session = boto3.Session()
    credentials = session.get_credentials()
    region = os.getenv("AWS_REGION")
    awsauth = AWS4Auth(credentials.access_key, credentials.secret_key, region, 'execute-api', session_token=credentials.token)
    return awsauth


response = requests.get('https://xxxxxxxxxx.execute-api.us-west-2.amazonaws.com/staging?group_name=test group one&requesting_user=user123@gmail.com, auth=get_auth())
```

**Comment by tedder** [comment]
Brandon, try using the `param` style with the request and let me know.
```
response = requests.get('https://xxxxxxxxxx.execute-api.us-west-2.amazonaws.com/staging',
  params={
    'group_name': 'test group one',
    'requesting_user': 'user123@gmail.com'
  }, auth=get_auth())

```

**Comment by bnorris823** [comment]
That worked thanks!

**Comment by tedder** [comment]
Great. I literally was explaining that to a junior coworker yesterday, if you pass a URL to requests it expects you to have already handled the URL encoding. If you pass the parts (params) it does it for you.
