### ISSUE TITLE
No module named 'requests_toolbelt'

### ISSUE THREAD

**Issue by wvidana** [tedder/requests-aws4auth#61]
Since yesterday night all my Lambda functions on AWS that use `requests-aws4auth` can't run, with the error:
```
No module named 'requests_toolbelt'
```

Guess there is some dependency issue with the pip package?

Adding that library to my requirements files fixes the problem.

NOTE: the functions are deployed using the SAM CLI

**Comment by tedder** [comment]
There's nothing in here named `requests_toolbelt`. Can you see where it's coming from? If so, reopen.

**Comment by wvidana** [comment]
Thanks for the response `tedder`, I thought that the issue came from this package, but it looks to be a dependency on `gql` https://github.com/graphql-python/gql/issues/327
