### ISSUE TITLE
Use Cross-account Roles?

### ISSUE THREAD

**Issue by parshnt** [tedder/requests-aws4auth#62]
is there a way to specify the arn of the role with requests-aws4auth?

context: I'm trying to implement cross-account access like this:
https://docs.aws.amazon.com/athena/latest/ug/cross-account-permissions.html

ps: happy to pick this if this needs to be added

Thanks

**Comment by tedder** [comment]
There isn't, but feel free to add- just make sure to give a decent test case.

**Comment by parshnt** [comment]
I was able to get this working for my use case using the AWS STS client to generate short-lived credentials and then implementing a custom class to refresh them at intervals.

closing this.
