### ISSUE TITLE
1.2.0 in PyPi differs from Github release

### ISSUE THREAD

**Issue by phillipberndt** [tedder/requests-aws4auth#64]
I installed 1.2.0 from PyPi, but it does not include #63.

**Comment by tedder** [comment]
I think I see what happened. Can you ensure it's fixed in 1.2.1 before I release it?

https://test.pypi.org/project/requests-aws4auth/1.2.1/

**Comment by phillipberndt** [comment]
Looks correct, thanks.

**Comment by tedder** [comment]
released: https://pypi.org/project/requests-aws4auth/1.2.1/
