### ISSUE TITLE
Problems with requests 2.9.0

### ISSUE THREAD

**Issue by asmaps** [tedder/requests-aws4auth#9]
There seems to be a problem with requests 2.9.0, with 2.8.1 everything works fine, but with 2.9.0 I get this error:

TransportError(403, '{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n\'PUT\n/xxxx\n\ncontent-type:text/plain; charset=UTF-8\nhost:xxxxx\nx-amz-content-sha256:xxxxx\nx-amz-date:20151221T154751Z\n\ncontent-type;host;x-amz-content-sha256;x-amz-date\nxxxxx\'\n\nThe String-to-Sign should have been\n\'AWS4-HMAC-SHA256\n20151221T154751Z\n20151221/eu-west-1/es/aws4_request\nxxxxxx\'\n"}')

**Comment by sam-washington** [comment]
Hmmm, all the live service tests run fine using Requests 2.9.1 on Python 2.7 and 3.4. Which version of Python are you using? Have you tried Requests 2.9.1?

**Comment by sam-washington** [comment]
I've run the test suite with Requests 2.9.0 with Pythons 2.7.10, 3.3.6, 3.4.3 and 3.5.0 and haven't hit any problems. Is it possible to provide the headers of a failed request, along with the error from AWS? You can get the headers with something like:

``` python
>>> response = requests.put('<URL>', auth=auth, ....)
>>> response.request.headers
{<Dict of headers, can you send this?>}
```

**Comment by asmaps** [comment]
I upgraded to 2.9.1, it works with it, so seems to be a problem in 2.9.0. I wouldn't bother too much with it, if it works with 2.9.1
